CREATE TABLE CART 
 (
 	ID	VARCHAR(40)	PRIMARY KEY
 );
 
CREATE TABLE ITEM 
 (
 	ID		VARCHAR(40)	PRIMARY KEY,
 	CART_ID	VARCHAR(40),
 	CONSTRAINT FK_CART
 		FOREIGN KEY(CART_ID)
 		REFERENCES CART(ID)
 );